service: lockbot

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    RESOURCES_TABLE_NAME: ${self:custom.resourcesTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [resourcesTable, Arn]

functions:
  slack-events-handler:
    handler: src/index.handler
    events:
      - http:
          method: post
          path: /slack/events

resources:
  Resources:
    resourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.resourcesTableName}
        AttributeDefinitions:
          - AttributeName: Resource
            AttributeType: S
          - AttributeName: Group
            AttributeType: S
        KeySchema:
          - AttributeName: Group
            KeyType: HASH
          - AttributeName: Resource
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

custom:
  stage: ${opt:stage, self:provider.stage}
  resourcesTableName: ${self:custom.stage}-lockbot-resources
  dynamodb:
    stages:
      - dev # https://bit.ly/35WR0TT
