name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
      - name: Setup AWS credentials
        run: |
          mkdir ~/.aws
          echo -e "[default]\naws_access_key_id=''\naws_secret_access_key=''" > ~/.aws/credentials
      - name: Setup Serverless Offline & Run Tests
        run: yarn ci
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
