name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@36eaff1005b37a22258716d4280f9e0377b834aa # v4.0.0
      - name: Setup AWS credentials
        run: |
          mkdir ~/.aws
          echo -e "[default]\naws_access_key_id=''\naws_secret_access_key=''" > ~/.aws/credentials
      - name: Setup Serverless Offline & Run Tests
        run: pnpm run ci
      - name: Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
