name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn eslint src/** test/**
      - run: yarn tsc --noEmit
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "123"
          aws-secret-access-key: "456"
          aws-region: eu-west-1
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
      - run: yarn jest --maxWorkers=1
