name: Deploy

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  deploy-dev:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      stage: dev
      environment: dev
    secrets: inherit
  deploy-prod:
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      stage: prod
      environment: prod
    secrets: inherit
